# Generated by Django 3.1.6 on 2021-04-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210401_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.DateTimeField(),
        ),
    ]
