# Generated by Django 3.1.6 on 2021-04-01 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210401_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
