# Generated by Django 3.1.6 on 2021-04-01 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210401_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
