# Generated by Django 3.1.6 on 2021-04-01 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20210401_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
