# Generated by Django 3.1.6 on 2021-04-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20210401_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='date',
        ),
    ]
